blueprint:
  name: Third Reality Zigbee Bulb Factory Reset
  description: Factory resets Third Reality Zigbee bulbs for re-pairing with a ZigBee Hub
  domain: automation
  input:
    input_boolean:
      name: Input Boolean
      description: This Input boolean will trigger the factory reset automation
      selector:
        entity:
          domain: input_boolean
    light_switch:
      name: Light Switch
      description: The light switch to use for factory resetting the Third Reality bulb
      selector:
        entity:
          domain: switch
trigger:
  - entity_id: !input input_boolean
    from: 'off'
    platform: state
    to: 'on'

action:
  - service: switch.turn_on
    entity_id: !input light_switch
  - delay: '3'
  - repeat:
      count: '5'
      sequence:
        - service: switch.turn_off
          entity_id: !input light_switch
        - delay: '1'
        - service: switch.turn_on
          entity_id: !input light_switch
        - delay: '1'
  - service: input_boolean.turn_off
    entity_id: !input input_boolean

